theme: jekyll-theme-minimal
title: Krogan Lab Web Resources 
logo: /assets/img/Krogan_lab_logo.png
description: Stable landing page with links to web resources relevant to Publications from the Krogan Lab at UCSF 
