theme: jekyll-theme-minimal
title:  
logo: /assets/img/Krogan_lab_logo.png
description: This page aims to be a permanent location providing links to web resources relevant to publications from the Krogan Lab at UCSF 
